model:
  device: "cuda"
  base_model_name_or_path: "models/gpt2"
  tokenizer_name_or_path: "models/gpt2"
  checkpoint_path: "${PROJECT_ROOT}/models/sim-cot-gpt2-coconut/checkpoint_28"
  add_latent_tokens: true
  start_latent_token_str: "<|start-latent|>"
  end_latent_token_str: "<|end-latent|>"
  latent_token_str: "<|latent|>"
  latent_init_token: "<<"
  # c_thought=2, max_latent_stage=5 -> 10 <|latent|> slots
  c_thought: 2
  max_latent_stage: 5
  num_latent_placeholders: 10
  teacher_target_template: "### {answer}"
  use_coconut_question_only: true
  align_latent_padding: true
generation_kwargs:
  max_new_tokens: 64
  temperature: 1.0
dataset_name: gsm8k
dataset_path: "data/gsm8k_local.jsonl"
prompt_template: "Question: {question}\nAnswer:"
steps: "1,2,3,4,5,6,7,8,9,10"
max_mean_steps: 10
