model:
  model_name_or_path: "models/gpt2"
  tokenizer_name_or_path: "models/gpt2"
  checkpoint_path: "${PROJECT_ROOT}/models/coconut_reproduction/gsm-cot-gpt2/checkpoint_15"
model_type: hf-auto
generation_kwargs: {}
dataset_name: gsm8k-aug
dataset_path: datasets/GSM8k-Aug
dataset_split: test
prompt_template: "Question: {question}\nAnswer:"
use_chat_template: false
