model:
  model_name_or_path: "${MODEL_DIR}/Llama-3.2-1B-Instruct"
  tokenizer_name_or_path: "${MODEL_DIR}/Llama-3.2-1B-Instruct"
model_type: hf-auto
generation_kwargs: {}
dataset_name: commonsenseqa
dataset_path: "data/commonsenseqa_cot_train_steps_1k.jsonl"
dataset_split: test
prompt_template: "{question}\nAnswer:"
use_chat_template: false
