model:
  device: "cuda"
  model_args:
    model_name_or_path: "${MODEL_DIR}/Qwen3-4B-Instruct-2507"
    ckpt_dir: "models/codi_reproduction/commonsense_codi_qwen3-4b"
    lora_r: 128
    lora_alpha: 32
    lora_dropout: 0.1
    full_precision: true
    token: null
  training_args:
    num_latent: 6
    inf_latent_iterations: 6
    use_lora: true
    use_prj: true
    prj_dim: 4096
    prj_dropout: 0.0
    prj_no_ln: false
    remove_eos: true
    greedy: true
    output_dir: "./outputs/codi_qwen3_4b"
    per_device_train_batch_size: 128
    per_device_eval_batch_size: 128
    bf16: false
  tokenizer_name_or_path: "${MODEL_DIR}/Qwen3-4B-Instruct-2507"
  generation_kwargs:
    max_new_tokens: 256
    temperature: 0.1
    top_k: 40
    top_p: 0.95
    greedy: true
  teacher_target_template: "The answer is: {answer}"
dataset_name: commonsenseqa
dataset_path: "data/commonsenseqa_local.jsonl"
prompt_template: "{question}\nAnswer:"
steps: "1,2,3,4,5,6"
max_mean_steps: 6
